version: '3.7'

networks:
  mynet:
    driver: bridge

volumes:
  data:

services:

  database:
    image: mariadb
    ports:
      - 3306:3306

    networks:
      - mynet
    container_name: database
    restart: always
    environment:
      MYSQL_USER: user2
      MYSQL_PASSWORD: myrootpass
      MARIADB_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: cinema

  webapp:
    build: .
    ports:
      - 8080:8080
    networks:
      - mynet
    restart: always
    container_name: webapp
    hostname: webservice
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/cinema
      SPRING_DATASOURCE_USERNAME: user2
      SPRING_DATASOURCE_PASSWORD: myrootpass
